# This workflow use pytest:
#  - Install Python dependencies.
#  - Run pytest for each of the supported Python versions ["3.8", "3.9", "3.10"]. 
# Running pytest with -m "no docker" to disable test that require a docker installation.

name: Pytest.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies.
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirement.txt
        python -m pip install -r tests/test-requirement.txt
    - name: Runnning tests with pytest.
      run: |
        pytest -m "not docker"
