name: Static Types Checker.

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install UV
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
      - name: Install dependencies.
        run: |
          python -m uv pip install -r requirement.txt
          python -m uv pip install -r tests/test-requirement.txt
      - name: Running static types checker.
        run: |
          mypy